@baseUrl = http://localhost:3030
@token = "foo"

GET {{baseUrl}}

###

POST {{baseUrl}}/api/shipping/reduce/product
content-type: application/json

{
    "id": "56564982",
    "quantity": "10",
    "email": "eklofcas@arcada.fi",
    "productName" : "Asus GeForce RTX 3080 ROG Strix - OC Edition -näytönohjain, 12GB GDDR6X"
}

###


 POST {{baseUrl}}/api/shipping/reduce?id=1&quantity=1&email=eklofcas@arcada.fi

