@baseUrl = http://localhost:3030
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjAzODk2MTAwY2RiODc5ZjA0MzRiZGIiLCJlbWFpbCI6InNoaXBwaW5nQHNlcnZpY2UuY29tIiwidXNlckxldmVsIjoidXNlciIsImlhdCI6MTY0NDUyMzc0OSwiZXhwIjoxNjQ5NzA3NzQ5fQ.q4QiUp7QQ9WKxmDe71C58DK1OyLTvC45KqSWnEPMkb0

GET {{baseUrl}}

###

POST {{baseUrl}}/api/shipping/reduce/product
Content-Type: application/json
Authorization: Bearer {{token}} 

{
    "id": "1000020000123",
    "quantity": "10",
    "email": "jepulis.jepjepjep@gmail.com"
}

###
POST {{baseUrl}}/api/shipping/reduce?id=1&quantity=1&email=jepulis.jepjepjep@gmail.com
Authorization: Bearer {{token}} 

